# Generated by Django 6.0 on 2026-03-03 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('versoes', models.CharField(max_length=100)),
                ('fornecedores', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_inventario', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.aplicacoes')),
            ],
        ),
        migrations.CreateModel(
            name='Registo_equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.aplicacoes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Registo_de_aplicacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.aplicacoes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.CharField(max_length=200)),
                ('logs_aplicacoes', models.ManyToManyField(to='ipma_agpp.aplicacoes')),
                ('logs_equipamentos', models.ManyToManyField(to='ipma_agpp.equipamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_aplicacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(auto_now_add=True)),
                ('atribuido_por', models.CharField(max_length=100)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.aplicacoes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.user')),
            ],
        ),
        migrations.AddField(
            model_name='aplicacoes',
            name='nomes',
            field=models.ManyToManyField(through='ipma_agpp.User_aplicacoes', to='ipma_agpp.user'),
        ),
        migrations.CreateModel(
            name='User_passes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encriptacao', models.CharField(max_length=100)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('expira_em', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.user')),
            ],
        ),
    ]
