# Generated by Django 6.0.2 on 2026-03-06 12:42

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('versoes', models.CharField(max_length=100)),
                ('fornecedores', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_inventario', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=100)),
                ('gerar_relatorio', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registo_de_aplicacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cargo', models.CharField(default='geral', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('grupo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.grupos')),
            ],
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Registo_equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.aplicacoes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.CharField(max_length=200)),
                ('logs_aplicacoes', models.ManyToManyField(to='ipma_agpp.aplicacoes')),
                ('logs_equipamentos', models.ManyToManyField(to='ipma_agpp.equipamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_aplicacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(auto_now_add=True)),
                ('atribuido_por', models.CharField(max_length=100)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.aplicacoes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.user')),
            ],
        ),
        migrations.AddField(
            model_name='aplicacoes',
            name='nomes',
            field=models.ManyToManyField(through='ipma_agpp.User_aplicacoes', to='ipma_agpp.user'),
        ),
        migrations.CreateModel(
            name='User_passes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encriptacao', models.CharField(max_length=100)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('expira_em', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.user')),
            ],
        ),
    ]
