# Generated by Django 6.0 on 2026-03-04 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipma_agpp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=100)),
                ('gerar_relatorio', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipma_agpp.grupos'),
        ),
    ]
